plugins {
    id("ktplus.base")
    id("ktplus.java")
    `maven-publish`
    `java-library`
}

dependencies {
    compileOnly(libs.platform.paper.api)
    compileOnly(libs.lib.jspecify)
    testImplementation(libs.platform.paper.api)
    testImplementation(libs.test.junit.jupiter)
    testRuntimeOnly(libs.test.junit.platform.launcher)
}

java {
    withJavadocJar()
    withSourcesJar()
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}

tasks.named<Javadoc>("javadoc") {
    options {
        this as StandardJavadocDocletOptions
        encoding = "UTF-8"
        charSet = "UTF-8"
        memberLevel = JavadocMemberLevel.PROTECTED
        addBooleanOption("Xdoclint:none", true)
        links("https://jd.papermc.io/paper/1.21.1/")
        links("https://jspecify.dev/docs/api/")
    }
    // Paper/JSpecify are compileOnly; still resolve for {@link} resolution when available.
    classpath += configurations.compileClasspath.get()
}

val generateApiVersion =
    tasks.register("generateApiVersion") {
        val outputDir = layout.buildDirectory.dir("generated/sources/apiVersion")
        inputs.property("projectVersion", project.version.toString())
        outputs.dir(outputDir)
        doLast {
            val packageDir = outputDir.get().asFile.resolve("com/monkey/ktplus/api")
            packageDir.mkdirs()
            packageDir.resolve("ApiVersion.java").writeText(
                """
                package com.monkey.ktplus.api;

                /**
                 * Build-time constants for the published KTPlus API artifact.
                 *
                 * <p>Generated by the {@code generateApiVersion} Gradle task. Prefer {@link
                 * KtPlus#version()} at runtime when the plugin is loaded; use this class for
                 * compile-time checks, dependency alignment, and shading diagnostics.
                 *
                 * @since 4.0.3
                 */
                public final class ApiVersion {
                    /**
                     * Maven/Gradle version of this {@code ktplus-api} artifact (for example {@code
                     * 4.0.3}).
                     */
                    public static final String VERSION = "${project.version}";

                    private ApiVersion() {}
                }
                """.trimIndent() + "\n",
            )
        }
    }

sourceSets {
    named("main") {
        java.srcDir(generateApiVersion.map { it.outputs.files.singleFile })
    }
}

tasks.named("compileJava") {
    dependsOn(generateApiVersion)
}

tasks.named("sourcesJar") {
    dependsOn(generateApiVersion)
}

tasks.named("javadoc") {
    dependsOn(generateApiVersion)
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            artifactId = "ktplus-api"
            from(components["java"])

            pom {
                name.set("KTPlus API")
                description.set(
                    "Public developer API for KTPlus — kill-effect services, events, and SPI for Paper/Folia plugins.",
                )
                url.set("https://github.com/MonkeyMoon104/KTPlus")
                licenses {
                    license {
                        name.set("GNU General Public License v3.0")
                        url.set("https://www.gnu.org/licenses/gpl-3.0.html")
                    }
                }
                developers {
                    developer {
                        id.set("monkeymoon104")
                        name.set("MonkeyMoon104")
                    }
                }
                scm {
                    url.set("https://github.com/MonkeyMoon104/KTPlus")
                    connection.set("scm:git:https://github.com/MonkeyMoon104/KTPlus.git")
                    developerConnection.set("scm:git:ssh://git@github.com/MonkeyMoon104/KTPlus.git")
                }
            }
        }
    }

    repositories {
        maven {
            name = "MonkeyRepo"
            url = uri("https://repo.monkeymoon104.it/release")
            credentials {
                username = providers.gradleProperty("monkeyrepo.user").orNull
                password = providers.gradleProperty("monkeyrepo.secret").orNull
            }
            authentication {
                create<BasicAuthentication>("basic")
            }
        }
    }
}
